### ISSUE TITLE
41.25 fps from sensor sc223a (sc5239s) 

### ISSUE THREAD

**Issue by RoboSchmied** [OpenIPC/firmware#1324]
You can get 41.24 fps on gk7205v210 with sensor sc5239s (which openipc labels sc223a), not only 30 fps.

Set `fps: 45` in /etc/majestic.yaml and `Isp_FrameRate=45` in /etc/sensors/sc223a_i2c_1080p.ini.
majestic output:
```
05:26:22  <       majestic> [    puts]                               linear mode
[Func]:cmos_fps_set [Line]:288 [Info]:Not support Fps: 45.000000
05:26:22  <       majestic> [    puts]                               === Smart SC223A_1080P_30FPS_10BIT_LINE_Init_OK!===
05:26:22  <       majestic> [     sdk] log_venc_chn@1256             H.264 1920x1080 45fps 6000Kbit  90 GOP
```
Majestic says it can `Not support Fps: 45`, but it is running faster  than only with fps: 30 settings. 

~~So should this be the new default for sc223a, even if the value you set (45 fps) is not exactly what you will get from sensor (41.24 fps) ?~~

The video looks more fluently. The frames are unique. No double frames are produced.

~~Can someone owning a sc223a please confirm the frame rate after changing the 2 lines?~~
Thank you.

**Comment by RoboSchmied** [comment]
Thank you for the info. 
Actually I have the sensor `sc5239s` (4MP) which OpenIPC recognizes as `sc223a` (2MP). And with the driver of sensor sc223a it can bring 41.24 fps.

OK, so I think the sensor distinction has to be corrected before changing any values for the *wrong sensor*.

**Comment by themactep** [comment]
Do you have a datasheet on your sensor? Read its hardware ID to confirm the model.

**Comment by themactep** [comment]
SC5239s would be a 5MP sensor, not 4MP. First digit denotes the resolution. If you were sold it as a 4MP, that should raise question if it is a legitimate hardware and if it is a 2MP SC223a instead.

**Comment by RoboSchmied** [comment]
> If you were sold it as a 4MP, that should raise question if it is a legitimate hardware and if it is a 2MP SC223a instead

I bought the sensor here: [aliexpress](https://de.aliexpress.com/item/1005003974380299.html). 
It is advertised as 4MP. The stock firmware offers the 4MP mode and it brings 4MP.

It is definitely not only 2 MP.

**Comment by themactep** [comment]
https://www.smartsenstech.com/en/mproducts_list?products_label=sc

**Comment by RoboSchmied** [comment]
> Very reassuring.

Sorry, I would not doubt your expertise.

> I have a bridge to sell you.

How much?  ;)

> https://www.smartsenstech.com/en/mproducts_list?products_label=sc

Thank you. I was unaware of the sensor labeling.



> Do you have a datasheet on your sensor?

No.

> Read its hardware ID to confirm the model.

Ok, I will try now.

**Comment by RoboSchmied** [comment]
> Read its hardware ID to confirm the model.

How do I get the hardware ID?
Here is the ipctool output:
```
root@openipc-gk7205v210:~# ipctool 
---
chip:
  vendor: Goke
  model: 7205V210
  id: 24662c1050a059e3
board:
  vendor: OpenIPC
  version: 2.4.01.19
ethernet:
  mac: "da:3c:1a:69:b2:bc"
  u-mdio-phyaddr: 1
  phy-id: 0x20669906
  d-mdio-phyaddr: 0
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x40000
      sha1: deca8aff
    - name: env
      size: 0x10000
      sha1: 6b5302d6
      contains:
        - name: uboot-env
          offset: 0x0
    - name: kernel
      size: 0x200000
      sha1: 381b79bd
    - name: rootfs
      size: 0x500000
      sha1: b323395a
    - name: rootfs_data
      size: 0xb0000
      path: /overlay,jffs2,rw
  size: 8M
  addr-mode: 3-byte
ram:
  total: 64M
  media: 24M
firmware:
  kernel: "4.9.37 (Fri Jan 19 23:35:21 CET 2024)"
  toolchain: buildroot-gcc-12.3.0
  main-app: wfb_tx
sensors:
- vendor: SmartSens
  model: SC223A
  control:
    bus: 0
    type: i2c
    addr: 0x60
  data:
    type: MIPI
    input-data-type: DATA_TYPE_RAW_10BIT
    lane-id:
      - 0
      - 1
    image: 1920x1080
  clock: 37.125MHz
```
