### ISSUE TITLE
Driver for IMX385 on Hi3516DV100

### ISSUE THREAD

**Issue by gitgayhub** [OpenIPC/firmware#153]
Hi, I've got [another camera](https://smtsec.en.alibaba.com/product/60842671862-803005151/H_265_2_0mp_Super_Starlight_IP_Camera_Module_Sony_IMX385_Hi3516D_CCTV_Smart_Security_IPC_PCB_IP_SMTSEC_Board_Camera_SIP_E385D.html) with the sensor imx385, but the soc is hi3516dv100 this time. I installed the newest OpenIPC firmware for hi3516dv100, but seems the imx385 driver and config file wasn't added for this soc

I've got a dump of the entire flash chip: [3516dv100_imx385_dump.zip](https://github.com/OpenIPC/firmware/files/7865217/3516dv100_imx385_dump.zip)

and the extracted rootfs: [3516dv100_imx385_rootfs.zip](https://github.com/OpenIPC/firmware/files/7865221/3516dv100_imx385_rootfs.zip)

```
hisilicon # print
bootdelay=1
baudrate=115200
ethaddr=00:00:23:34:45:66
bootfile="uImage"
bootcmd=sf probe 0;sf read 0x82000000 0x80000 0x280000;bootm 0x82000000
configFlag=ok
cpuFlag=ok
cpuType=3516a
sensorFlag=no
sensorType=53
filesize=39840
fileaddr=82000000
netmask=255.255.255.0
bootargs=mem=108M console=ttyAMA0,115200 root=/dev/mtdblock1 rootfstype=jffs2 mtdparts=hi_sfc:3M(boot),13M(rootfs)
stdin=serial
stdout=serial
stderr=serial
verify=n
ver=U-Boot 2010.06 (Sep 22 2017 - 09:17:14)
mdio_intf=rmii
hisicpu=hi3516d
ipaddr=192.168.2.22
serverip=192.168.2.88
```
I modified bootargs and boocmd to suite OpenIPC, please let me know if there's anything wrong
```
mem=108M totalmem=128M console=ttyAMA0,115200 panic=20 root=/dev/mtdblock2 rootfstype=squashfs init=/init mtdparts=hi_sfc:3072k(boot),2048k(kernel),5120k(rootfs),-(rootfs_data)
bootcmd=sf probe 0;sf read 0x82000000 0x300000 0x300000;bootm 0x82000000
```

```
/ # cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00300000 00010000 "boot"
mtd1: 00d00000 00010000 "rootfs"

```

```
/usr # ./ipctool
---
chip:
  vendor: HiSilicon
  model: 3516DV100
ethernet:
  mac: "e6:98:25:xxxxxxx"
  u-mdio-phyaddr: 86
  phy-id: 0xa5a5a5a5
  d-mdio-phyaddr: a5a5
rom:
  - type: nor
    block: 64K
    partitions:
      - name: boot
        size: 0x300000
        sha1: b6d9797f
        contains:
          - name: uboot-env
            offset: 0x40000
      - name: rootfs
        size: 0xd00000
        sha1: a11e3d0f
    size: 16M
    addr-mode: 3-byte
ram:
  total: 128M
firmware:
  u-boot: "2010.06 (Sep 22 2017 - 09:17:14)"
  kernel: "3.4.35 (Wed Aug 16 16:10:11 CST 2017)"
  toolchain: gcc version 4.8.3 20131202 (prerelease) (Hisilicon_v300)
  libc: uClibc 0.9.33.2
```
