### ISSUE TITLE
Backup/Flash without tftp (hi3516ev200)

### ISSUE THREAD

**Issue by Pimmetje** [OpenIPC/firmware#17]
I am trying to flash a hi3516ev200 without tftp (i am unable to get a link).

Normal boot:
```
System startup

Uncompress Ok!

U-Boot 2016.11-g2fc5f58-dirty (Sep 06 2019 - 15:13:30 +0800)hi3516ev200

Relocation Offset is: 0371b000
Relocating to 43f1b000, new gd at 43edaef0, sp at 43edaed0
SPI Nor:  eFlashType: 24.
Flash Name: XM_XT25F64B-S{0xB4017), 0x800000.
@hifmc_spi_nor_probe(), XmSpiNor_ProtMgr_probe(): OK.
@XmSpiNor_enableQuadMode(), Quad was Disabled, SRx: [2, 0x0].
CONFIG_CLOSE_SPI_8PIN_4IO = y.
read->iftype[0: STD, 1: DUAL, 2: DIO, 3: QUAD, 4: QIO]: 1.
Current level[6], lock_level_max:7.
at xm_get_locked_range() sr:0x18, level:6.
lk[6 => 0x400000]
SRx val: {[1, 0x38], [1, 0x0], [0, 0x0], [0, 0x0]}.
In:    serial
Out:   serial
Err:   serial
Net:   eth0
Hit ctrl+c to stop autoboot:  0
@do_spi_flash_probe() flash->erase_size:65536
device 0 offset 0x40000, size 0x550000

SF: 5570560 bytes @ 0x40000 Read: OK
srcAddr 0x43000000, dstAddr 0x42000000
created_inode 0x43edb810
find_squashfs_file: name bin, start_block 0, offset 2001, type 1
find_squashfs_file: name boot, start_block 0, offset 2181, type 1
read inode: name boot, sb 0, of 2181, type 1
find_squashfs_file: name uImage, start_block 0, offset 2033, type 2
read inode: name uImage, sb 0, of 2033, type 2
write_file: regular file, blocks 29
len 1861831
### FS load complete: 1861831 bytes loaded to 0x42000000
## Booting kernel from Legacy Image at 42000000 ...
   Image Name:   Linux-4.9.37
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    1861767 Bytes = 1.8 MiB
   Load Address: 40008000
   Entry Point:  40008000
   Loading Kernel Image ... OK

Starting kernel ...

Uncompressing Linux... done, booting the kernel.
```
I won't get any output afterwards. 

Interrupting:
```
System startup

Uncompress Ok!

U-Boot 2016.11-g2fc5f58-dirty (Sep 06 2019 - 15:13:30 +0800)hi3516ev200

Relocation Offset is: 0371b000
Relocating to 43f1b000, new gd at 43edaef0, sp at 43edaed0
SPI Nor:  eFlashType: 24.
Flash Name: XM_XT25F64B-S{0xB4017), 0x800000.
@hifmc_spi_nor_probe(), XmSpiNor_ProtMgr_probe(): OK.
@XmSpiNor_enableQuadMode(), Quad was Disabled, SRx: [2, 0x0].
CONFIG_CLOSE_SPI_8PIN_4IO = y.
read->iftype[0: STD, 1: DUAL, 2: DIO, 3: QUAD, 4: QIO]: 1.
Current level[6], lock_level_max:7.
at xm_get_locked_range() sr:0x18, level:6.
lk[6 => 0x400000]
SRx val: {[1, 0x38], [1, 0x0], [0, 0x0], [0, 0x0]}.
In:    serial
Out:   serial
Err:   serial
Net:   eth0
Hit ctrl+c to stop autoboot:  0
hisilicon 
```

Help
```
hisilicon # help
?       - alias for 'help'
base    - print or set address offset
bdinfo  - print Board Info structure
bitwait - bit compare and wait for equal
boot    - boot default, i.e., run 'bootcmd'
bootd   - boot default, i.e., run 'bootcmd'
bootm   - boot application image from memory
bootp   - boot image via network using BOOTP/TFTP protocol
clearenv- clear env partition.
cmp     - memory compare
coninfo - print console devices and information
cp      - memory copy
crc32   - checksum calculation
dcache  - enable or disable data cache
ddr     - ddr training function
dispaddr- display the value of 'addr'
dispenv - display the value of 'env_var'
dispver - display the uboot version
editenv - edit environment variable
env     - environment handling commands
erase   - erase FLASH memory
exit    - exit script
false   - do nothing, unsuccessfully
flinfo  - print FLASH memory information
flwrite - SPI flash sub-system
getinfo - print hardware information
go      - start application at address 'addr'
gzwrite - unzip and write memory to block device
help    - print command description/usage
icache  - enable or disable instruction cache
loadb   - load binary file over serial line (kermit mode)
loadx   - load binary file over serial line (xmodem mode)
loady   - load binary file over serial line (ymodem mode)
loop    - infinite loop on address range
md      - memory display
mii     - MII utility commands
mm      - memory modify (auto-incrementing address)
mw      - memory write (fill)
nm      - memory modify (constant address)
part    - disk partition related commands
ping    - send ICMP ECHO_REQUEST to network host
printenv- print environment variables
protect - enable or disable FLASH write protection
pxe     - commands to get and boot from pxe files
reset   - Perform RESET of the CPU
run     - run commands in an environment variable
saveenv - save environment variables to persistent storage
setenv  - set environment variables
sf      - SPI flash sub-system
showvar - print local hushshell variables
sleep   - delay execution for some time
squashfsload- fsload  - load binary file from a filesystem image

sysboot - command to get and boot from syslinux files
test    - minimal test like /bin/sh
tftpboot- boot image via network using TFTP protocol
true    - do nothing, successfully
unzip   - unzip a memory region
version - print monitor, compiler and linker version
waitus  - wait for n us
```

```
hisilicon # bdinfo
arch_number = 0x00001F40
boot_params = 0x40000100
DRAM bank   = 0x00000000
-> start    = 0x40000000
-> size     = 0x04000000
eth0name    = eth0
ethaddr     = 00:12:31:xx:xx:xx
current eth = eth0
ip_addr     = 192.168.2.168
baudrate    = 115200 bps
TLB addr    = 0x43FF0000
relocaddr   = 0x43F1B000
reloc off   = 0x0371B000
irq_sp      = 0x43EDAEE0
sp start    = 0x43EDAED0
```

I played around with some commands. (setting other IP's/subnets etc).  But i was unable to get the ethernet leds to turn on. 
So i guess it would require flashing it over serial only.

I have seen a tool (ubootwrite.py) that could help with that. But that's something i still need to find out.

**Comment by Pimmetje** [comment]
Using https://m.habr.com/en/post/486856/ and https://github.com/tothi/hs-dvr-telnet

and 

```
from telnetlib import Telnet


def telnet_login(password):
    print('Attempting', password)
    with Telnet('10.9.2.200', 23) as tn:
        username = 'root'
        tn.set_debuglevel(1000)
        tn.read_until(b"login: ")
        tn.write(username.encode('ascii') + b"\n")
        tn.read_until(b"Password: ")
        tn.write(password.encode('ascii') + b"\n")
        data = tn.read_until(b"Login incorrect")
        if b'Login incorrect' in data:
            return False
        return True

file1 = open('passwords.txt', 'r')
lines = file1.readlines()
for line in lines:
    if telnet_login(line):
        break

```

passwords.txt
```
00000000
059AnkJ
4uvdzKqBkj.jg
7ujMko0admin
7ujMko0vizxv
123
1111
1234
1234qwer
2601hx
12345
54321
123456
666666
888888
1111111
/*6.=_ja
anko
anni2013
annie2012
avtech97
cat1029
ccadmin
cxlinux
default
dreambox
fxjvt1805
hdipc%No
hi3518
hichiphx
hipc3518
hkipc2016
hslwificam
ikwb
ipc71a
IPCam@sw
ivdev
juantech
jvbzd
jvtsmart123
klv123
klv1234
meinsm
OxhlwSG8
pass
password
realtek
root
hi3518
S2fGqNFs
service
smcadmin
supervisor
support
system
tech
tlJwpbo6
ubnt
user
vhd1206
vizxv
xc3511
xmhdipc
zlxx.
Zte521
```

My telnet password is xmhdipc (username root)
Now i have to find a way to extract data and upload new programs.

**Comment by widgetii** [comment]
Try to run [ipctool](https://github.com/OpenIPC/ipctool/releases/download/latest/ipctool) on it

**Comment by Pimmetje** [comment]
I was able to transfer the ipctool using serial

```
---
board:
  vendor: Xiongmai
  model: HI3516EV200_50H20AI_S38
  cloudId: 828e52bc1xxxxxxx
chip:
  vendor: HiSilicon
  model: 3516EV200
  id: 02383a867e0038e9ee70030ac2d7f693262867xxxxxxxxx
ethernet:
  mac: "00:12:31:xx:xx:xx"
  u-mdio-phyaddr: 1
  phy-id: 0x206xxxxx
  d-mdio-phyaddr: 0
rom:
  - type: nor
    block: 64K
    chip:
      name: "XM_XT25F64B-S"
      id: 0x0b4017
    partitions:
      - name: boot
        size: 0x40000
        sha1: 9c3185f5
        contains:
          - name: xmcrypto
            offset: 0x2fc00
          - name: uboot-env
            offset: 0x30000
      - name: romfs
        size: 0x2e0000
        path: /,squashfs
        sha1: 548fe861
      - name: user
        size: 0x420000
        path: /usr,squashfs
        sha1: 64b32f0a
      - name: web
        size: 0x40000
        path: /mnt/web,cramfs
        sha1: ffac9f55
      - name: custom
        size: 0x30000
        path: /mnt/custom,cramfs
        sha1: 3ef98758
      - name: mtd
        size: 0x50000
        path: /mnt/mtd,jffs2,rw
    size: 8M
    addrMode: 3-byte
ram:
  total: 64M
  media: 26M
firmware:
  u-boot: "2016.11 (Oct 29 2018 - 16:06:38)"
  kernel: "4.9.37 (Fri Sep 6 15:29:30 CST 2019)"
  toolchain: gcc version 6.3.0 (Heterogeneous Compiler&Codesign V100R002C00B003)
  libc: uClibc 0.9.33.2
  sdk: "Hi3516EV200_MPP_V1.0.1.1 B030 Release (Jun 17 2019, 11:19:14)"
  god-app: /usr/bin/Sofia
sensors:
- vendor: Sony
  model: IMX307
  control:
    bus: 0
    type: i2c
    addr: 0x34
  data:
    type: MIPI
    input_data_type: DATA_TYPE_RAW_12BIT
    laneId:
    - 0
    - 1
    image: 1920x1080
  clock: 37.125MHz
```
