### ISSUE TITLE
IMX327 support for Hi3516AV200

### ISSUE THREAD

**Issue by gitgayhub** [OpenIPC/firmware#201]
Hi, thanks for the great project again

I'm wondering if you can add support for imx327 on hi3516av200 platform. I've got a camera with telnet access to stock firmware so I already got the libsns file but don't know how to write the config file
[imx327.zip](https://github.com/OpenIPC/firmware/files/8246696/imx327.zip)

I can arrange remote telnet access if needed

Thank you very much

ipctool inside stock firmware
```
/mnt/nfs # ./ipctool
---
chip:
  vendor: HiSilicon
  model: 3516AV200
ethernet:
  mac: "xxxxxx"
  phy-mode: rmii
rom:
  - type: nand
    block: 256K
    partitions:
      - name: uboot
        size: 0x80000
        sha1: 83c5691d
      - name: ubootenv
        size: 0x80000
        sha1: e5bc57ab
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel
        size: 0x400000
        sha1: 2a81aa03
      - name: rootfs
        size: 0x2000000
        path: /,yaffs2
        sha1: f7cd3716
      - name: appfs
        size: 0x6400000
        path: /home,yaffs2,rw
      - name: datafs
        size: 0x17700000
        path: /data_fs,yaffs2,rw
    size: 512M
ram:
  total: 512M
  media: 256M
firmware:
  u-boot: "2010.06 (Jan 10 2019 - 12:48:22)"
  kernel: "3.18.20 (SMP Tue Dec 4 17:45:49 CST 2018)"
  toolchain: gcc version 4.9.4 20150629 (prerelease) (Hisilicon_v600_20170615)
  sdk: "Hi3519V101_MPP_V2.0.4.0 B040 Release (Nov 10 2017, 14:28:05)"
  main-app: ./face
sensors:
- vendor: Sony
  model: IMX327
  control:
    bus: 0
    type: spi
  vicap0-state: up
  vicap1-state: down
  data:
    vicap0-input: MIPI0
    mipi0-type: MIPI
```

ipctool inside openipc:

```
root@openipc-hi3516av200:/etc/sensors# ipctool

The ipctool installed as remote GitHub plugin

---
board:
  vendor: OpenIPC
  version: 2.2.03.14
chip:
  vendor: HiSilicon
  model: 3516AV200
ethernet:
  mac: "00:00:23:34:45:66"
  phy-mode: rmii
rom:
  - type: nand
    block: 256K
    partitions:
      - name: boot
        size: 0x80000
        sha1: 83c5691d
      - name: ubootenv
        size: 0x80000
        sha1: ccbef8e6
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel_old
        size: 0x400000
        sha1: 2a81aa03
      - name: rootfs_old
        size: 0x2000000
        sha1: ffe4896d
      - name: appfs
        size: 0x6400000
        sha1: 2c1800fc
      - name: kernel
        size: 0x200000
        sha1: 6645c1c6
      - name: rootfs
        size: 0x500000
        path: /,squashfs
        sha1: e7d58ee8
      - name: rootfs_data
        size: 0x500000
        path: /overlay,jffs2,rw
      - name: others
        size: 0x16b00000
        sha1: 3faf6123
    size: 512M
ram:
  total: 256M
firmware:
  u-boot: "2010.06 (Jan 10 2019 - 12:48:22)"
  kernel: "3.18.20 (SMP Mon Mar 14 03:45:33 UTC 2022)"
  toolchain: gcc version 7.5.0 (Buildroot -gaa4bdd6)

```
