### ISSUE TITLE
Изменить структуру profiler'а

### ISSUE THREAD

**Issue by p0i5k** [OpenIPC/firmware#240]
Сейчас /usr/sbin/profiler содержит информацию о gpio для всех процессоров и производителей.
Перенести из него информацию в файл yaml /etc/profiler.full, который будет процессорозависимым и содержать информацию о выводах от всех производителей.

Пример для процессора hi3516ev200:
```
Herospeed:
  gpio:
    ircut1: 12 
    ircut2: 13
    irctl: 4
    alm_in: 15
    alm_out: 14
Xiongmai:
  gpio:
    ircut1: 8
    ircut: 29
    irstatus: 15
    irctl: 16
    alm_in: 4
    alm_out: 55
    eth_act: 14
    eth_sta: 12
    reset: 0
```
