### ISSUE TITLE
Use external config for url in sysupgrade

### ISSUE THREAD

**Issue by p0i5k** [OpenIPC/firmware#453]
Вынести url'ы обновления в /etc/channels, пример файла:
```
system:
  profile: ultimate
  url: https://github.com/OpenIPC/firmware/releases/download/latest/openipc.gk7205v300-ultimate-br.tgz
streamer:
  name: majestic
  url: http://openipc.s3-eu-west-1.amazonaws.com/majestic.gk7205v200.ultimate.master.tar.bz2
webui:
  branch: dev
  url: https://github.com/OpenIPC/microbe-web/archive/refs/heads/dev.zip
```
