### ISSUE TITLE
Fails to detect T20 processor, which causes Majestic to crash on startup

### ISSUE THREAD

**Issue by felipecrs** [OpenIPC/firmware#607]
Hello,

As pointed in Telegram, OpenIPC fails to detect my T20 processor and this causes some side-effects like Majestic crashing on startup with the following:

![image](https://user-images.githubusercontent.com/29582865/211323594-dfc3fd37-7261-42a8-bbdf-ae96b180cf48.png)

The boot logs says:

```
--------------------
ISP_PARAM: isp_clk=90000000
SENSOR: sc2235
SENSOR_PARAM:
--------------------
insmod: can't insert '/lib/modules/3.10.14/ingenic/tx-isp-unknown.ko': No such file or directory
```

`fw_setenv soc t20` does not seem to help:

![image](https://user-images.githubusercontent.com/29582865/211323206-b4773ad9-e935-451e-ad76-1ee4e8ec5742.png)

The workaround I found was:

```console
cp /lib/modules/3.10.14/ingenic/tx-isp-t20.ko /lib/modules/3.10.14/ingenic/tx-isp-unknown.ko
```

Which, in case the proper fix is too hard, I believe could be included in the T20 firmware package by default (it's T20 anyway).

This is ipctool's output:

```
# ipctool
The ipctool installed as remote GitHub plugin

---
chip:
  vendor: Ingenic
  model: unknown
board:
  vendor: OpenIPC
  version: 2.2.12.26
ethernet:
  mac: "00:11:22:33:44:55"
rom:
  - type: nor
    block: 32K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 477a24e9
      - name: env
        size: 0x10000
        sha1: 4f1ba5df
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel
        size: 0x300000
        sha1: f6cb7d04
      - name: rootfs
        size: 0xa00000
        path: /,squashfs
        sha1: 641b53ef
      - name: rootfs_data
        size: 0x2b0000
        path: /overlay,jffs2,rw
    size: 16M
ram:
  total: 64M
  media: 0M
firmware:
  kernel: "3.10.14 (PREEMPT Mon Dec 26 12:30:51 UTC 2022)"
  toolchain: gcc version 8.4.0 (Buildroot -gff5aa3b6-dirty)
```

Web:

![image](https://user-images.githubusercontent.com/29582865/211323916-29b15aff-4407-4b16-9ea7-22caeb1503c6.png)

**Comment by dimerr** [comment]
When was the last time you've actually ran ipctool?

**Comment by FlyRouter** [comment]
Please wait 
Work is underway to standardize calls for different processors.

**Comment by felipecrs** [comment]
January 4, 2023. Have things changed since then?

Unfortunately my camera is not accessible right now, so I won't be able to run ipctool at this moment. Sorry.

If things have changed since then, feel free to "park" this.

**Comment by felipecrs** [comment]
Processor detector is working fine now, yay!

**Comment by felipecrs** [comment]
Out of curiosity, running ipctool today gives:

```
chip:
  vendor: Ingenic
  model: T20L
board:
  vendor: OpenIPC
  version: 2.3.01.31
ethernet:
  mac: "00:c1:29:01:04:73"
rom:
  - type: nor
    block: 32K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 477a24e9
      - name: env
        size: 0x10000
        sha1: 1102f6f7
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel
        size: 0x300000
        sha1: ce079091
      - name: rootfs
        size: 0xa00000
        path: /,squashfs
        sha1: 7f64d228
      - name: rootfs_data
        size: 0x2b0000
        path: /overlay,jffs2,rw
    size: 16M
ram:
  total: 64M
  media: 20M
firmware:
  kernel: "3.10.14 (PREEMPT Tue Jan 31 20:35:05 UTC 2023)"
  toolchain: gcc version 8.4.0 (Buildroot -gff5aa3b6-dirty)
  main-app: /tmp/ipctool
```

Which fixed the processor detection, although it does not yet detect my sensor (sc2235). Microbe UI detects it though.
