### ISSUE TITLE
mt7601u kernel module missing in hi3518ev100-lite firmware

### ISSUE THREAD

**Issue by databus23** [OpenIPC/firmware#941]
Hi,

I just managed to flash the `openipc-hi3518ev100-lite-16mb.bin` firmware onto a Hikam S5 Wireless-only webcam but have no working networking.
The initial problem seem to be that the firmware has no `mt7601u` that can be loaded to support the usb wireless adapter.

```
root@openipc-hi3518ev100:/lib/modules# lsusb
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0001
Bus 001 Device 002: ID 148f:7601
root@openipc-hi3518ev100:/lib/modules# modprobe mt7601u
modprobe: module mt7601u not found in modules.dep
```

The firmware for the wireless adapter is there though:
```
root@openipc-hi3518ev100:/lib/firmware# find .
.
./mediatek
./mediatek/mt7601u.bin
./mt7601u.bin
./rtlwifi
./rtlwifi/rtl8188eufw.bin
```

Any ideas how I can fix that?

iptool output:
```
---
chip:
  vendor: HiSilicon
  model: 3518EV100
board:
  possible-IR-cut-GPIO: 49,72,78
ethernet:
  mac: "e0:b9:4d:4b:ac:8b"
  u-mdio-phyaddr: 1
  phy-id: 0x0000ffff
  d-mdio-phyaddr: 0
  phy-mode: mii
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x80000
      sha1: aa1f5e70
    - name: kernel
      size: 0x300000
      sha1: a7f8daad
    - name: rootfs
      size: 0x780000
      path: /,squashfs
      sha1: cebe0bc8
    - name: rom
      size: 0x100000
      path: /rom,jffs2,rw
    - name: app
      size: 0x400000
      path: /npc,jffs2,rw
  size: 16M
  addr-mode: 3-byte
ram:
  total: 64M
  media: 26M
firmware:
  kernel: "3.0.8 (Mon May 19 23:21:54 PDT 2014)"
  toolchain: gcc version 4.4.1 (Hisilicon_v100(gcc4.4-290+uclibc_0.9.32.1+eabi+linuxpthread))
  sdk: "Hi3518_MPP_V1.0.8.1  (Mar 18 2014, 11:53:10)"
  main-app: /npc/npc
```
